генерация 25 карточек фотографий
htmlacademy-javascript/2098917-kekstagram-28 pull request #3
Opened 2023-03-01 18:59 UTC by MissShim

2023-03-01 19:01 UTC, MissShim commented
Консоль линтеру не нравится, не вызывать функцию после создания - тоже не нравится... поэтому я просто написала вызов функции без вывода в консоль, это ок?

2023-03-05 07:45 UTC, pavel-nyukalo requested changes

2023-03-05 07:45 UTC, pavel-nyukalo commented on js/main.js
> +function createUniqueId (a, b) {
`a, b` в этих функциях не очень информативны при просмотре функций. Поэтому я бы предложил их назвать как минимум `min` и `max` - уже больше информации

2023-03-05 07:45 UTC, pavel-nyukalo commented on js/main.js
> +    photoLikes: getRandomInteger(15, 200),
15 и 200 тоже магические числа и им тоже надо константы выделить по критерию

2023-03-06 16:15 UTC, pavel-nyukalo approved these changes

2023-03-06 16:15 UTC, merged