Открытие окна загрузки фото
htmlacademy-javascript/2098917-kekstagram-28 pull request #8
Opened 2023-03-28 13:02 UTC by MissShim

Вроде все работает, но я не поняла, что за косяк происходит с отправкой формы. В окне бразуера появляется cannot POST и в консоли две ошибки, связанные с localhost. Это так и надо, или в чем-то косяк?

2023-03-29 06:24 UTC, pavel-niukalo requested changes

2023-03-29 06:24 UTC, pavel-niukalo commented on js/main.js
> +
Я бы предложил навешать эти обработчики внутри `upload-image.js`, а сюда просто импортнуть сам модуль

2023-03-29 06:24 UTC, pavel-niukalo commented on js/upload-image.js
> +const validHashtag = /^#[a-zа-яё0-9]{1,19}$/i;
1. Константы должны быть перед основным кодом в самом начале, после импортов
2. Переменную хештега я бы тоже записал как константу, поскольку она не меняется

2023-03-29 06:24 UTC, pavel-niukalo commented on js/upload-image.js
> +  const LowerCase = tags.map((tag) => tag.toLowerCase());
`LowerCase` это не класс и не перечисление, а просто переменная, поэтому ее нужно записать в `camelCase`

![image](https://user-images.githubusercontent.com/52506235/228444068-60aafc80-e40b-40d3-9e29-2c096fe6eb7a.png)

2023-03-29 06:24 UTC, pavel-niukalo commented on js/upload-image.js
> +imgUploadForm.addEventListener('submit', onSubmit);
Вот тут как раз уже навешан обработчик на форму, поэтому из `main.js` как раз удалить нужно

2023-03-29 11:29 UTC, pavel-niukalo requested changes

2023-03-29 11:29 UTC, pavel-niukalo commented on js/upload-image.js
> +const VALID_HASHTAGS = /^#[a-zа-яё0-9]{1,19}$/i;
Константы у нас должны идти первыми сразу после импортов. То есть сначала импорты, потом константы, потом основной код (создание переменных, в данном случае это у нас DOM-элементы, тоже относится к основному коду)

То бишь структура модуля, при условии что он "полный" (под полным имею ввиду, что у него есть и импорты, и константы, и экспорты и тд) будет такая

```js
import ...
import ...
// еще сколько-то ипортов

const CONSTANT = ...
// Еще константы

const simpleVariable = ...
// Просто переменные всякие

const checkAnything = () => {}
// Остальные функции и тд

export { ... }
```

2023-03-29 20:47 UTC, KuzminaPolina commented on js/upload-image.js
> +const VALID_HASHTAGS = /^#[a-zа-яё0-9]{1,19}$/i;
а ой, хорошо, извини >_<

2023-03-30 11:31 UTC, pavel-niukalo approved these changes

2023-03-30 11:31 UTC, merged